# Generated by Django 2.2.4 on 2019-10-28 04:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requestlist',
            fields=[
                ('request_id', models.TextField(default='something', primary_key=True, serialize=False)),
                ('request_owner', models.TextField(default='something')),
                ('request_status', models.TextField(default='unassigned')),
                ('request_pid', models.IntegerField(default=0)),
                ('vader_status', models.TextField(default='unassigned')),
                ('vader_pid', models.IntegerField(default=0)),
                ('textblob_status', models.TextField(default='unassigned')),
                ('textblob_pid', models.IntegerField(default=0)),
                ('stanfordNLP_status', models.TextField(default='unassigned')),
                ('stanfordNLP_pid', models.IntegerField(default=0)),
                ('sentiWordNet_status', models.TextField(default='unassigned')),
                ('sentiWordNet_pid', models.IntegerField(default=0)),
                ('request_issued_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('request_completed_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('file_path', models.TextField(default='/')),
            ],
        ),
        migrations.CreateModel(
            name='requestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.TextField(default='something')),
                ('vaderConfusionMatrix', models.CharField(default='SOME STRING', max_length=200)),
                ('vaderPrecise', models.FloatField(default=150.0)),
                ('vaderRecall', models.FloatField(default=150.0)),
                ('vaderF1Score', models.FloatField(default=150.0)),
                ('textblobConfusionMatrix', models.CharField(default='SOME STRING', max_length=200)),
                ('textblobPrecise', models.FloatField(default=150.0)),
                ('textblobRecall', models.FloatField(default=150.0)),
                ('textblobF1Score', models.FloatField(default=150.0)),
                ('sentiWordNetConfusionMatrix', models.CharField(default='SOME STRING', max_length=200)),
                ('sentiWordNetPrecise', models.FloatField(default=150.0)),
                ('sentiWordNetRecall', models.FloatField(default=150.0)),
                ('sentiWordNetF1Score', models.FloatField(default=150.0)),
                ('stanfordNLPConfusionMatrix', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('key', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('request_id', models.TextField(default='something')),
                ('tweet_id', models.TextField(default='tweet_id')),
                ('tweet_content', models.TextField(default='tweet_content')),
                ('tweet_annotation', models.TextField(default='tweet_annotation')),
                ('vaderScores', models.FloatField(default=150.0)),
                ('vaderPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('vaderCountpol', models.CharField(default='SOME STRING', max_length=200)),
                ('textblobScores', models.FloatField(default=150.0)),
                ('textblobPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('textblobCountpol', models.CharField(default='SOME STRING', max_length=200)),
                ('sentiWordNetScores', models.FloatField(default=150.0)),
                ('sentiWordNetPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('sentiWordNetCountpol', models.CharField(default='SOME STRING', max_length=200)),
                ('stanfordNLPPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('stanfordNLPCountpol', models.CharField(default='SOME STRING', max_length=200)),
                ('stanfordNLPConfusionMatrix', models.FloatField(default=150.0)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
            ],
        ),
    ]
