# Generated by Django 2.2.4 on 2019-12-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='requestName',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='userEmail',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='request_key',
            field=models.IntegerField(default=0),
        ),
    ]
