# Generated by Django 2.2.3 on 2019-07-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
