# Generated by Django 2.2.3 on 2019-09-17 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0002_auto_20190717_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAResult',
            fields=[
                ('ids', models.CharField(default='SOME STRING', max_length=200, primary_key=True, serialize=False)),
                ('tweetContent', models.CharField(default='SOME STRING', max_length=200)),
                ('vaderTweetScore', models.FloatField(default=150.0)),
                ('vaderTweetPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('textblobTweetScore', models.FloatField(default=150.0)),
                ('textblobTweetPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('stanfordNLPTweetPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('sentiWordNetTweetScore', models.FloatField(default=150.0)),
                ('sentiWordNetTweetPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('tweetKappa', models.FloatField(default=150.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SAResultSentence',
            fields=[
                ('ids', models.CharField(default='SOME STRING', max_length=200, primary_key=True, serialize=False)),
                ('vaderSentenceScoreList', models.CharField(default='SOME STRING', max_length=200)),
                ('vaderSentencePolarityList', models.CharField(default='SOME STRING', max_length=200)),
                ('vaderAverage', models.FloatField(default=150.0)),
                ('vaderMajority', models.CharField(default='SOME STRING', max_length=200)),
                ('textblobSentenceScoreList', models.CharField(default='SOME STRING', max_length=200)),
                ('textblobSentencePolarityList', models.CharField(default='SOME STRING', max_length=200)),
                ('textblobAverage', models.FloatField(default=150.0)),
                ('textblobMajority', models.CharField(default='SOME STRING', max_length=200)),
                ('stanfordNLPSentencePolarityList', models.CharField(default='SOME STRING', max_length=200)),
                ('stanfordNLPMajority', models.CharField(default='SOME STRING', max_length=200)),
                ('sentiWordNetSentenceScoreList', models.CharField(default='SOME STRING', max_length=200)),
                ('sentiWordNetSentencePolarityList', models.CharField(default='SOME STRING', max_length=200)),
                ('sentiWordNetAverage', models.FloatField(default=150.0)),
                ('sentiWordNetMajority', models.CharField(default='SOME STRING', max_length=200)),
                ('sentenceKappa', models.FloatField(default=150.0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
