# Generated by Django 2.2.4 on 2019-12-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0002_auto_20191203_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='isMailSended',
            field=models.TextField(default='NOT YET'),
        ),
    ]
