# Generated by Django 2.2.6 on 2019-11-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0002_remove_tweet_stanfordnlpconfusionmatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentenceResult',
            fields=[
                ('key', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('request_id', models.TextField(default='something')),
                ('tweet_id', models.TextField(default='tweet_id')),
                ('sentenceID', models.IntegerField(default=0)),
                ('vaderScores', models.FloatField(default=150.0)),
                ('vaderPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('textblobScores', models.FloatField(default=150.0)),
                ('textblobPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('sentiWordNetScores', models.FloatField(default=150.0)),
                ('sentiWordNetPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('stanfordNLPPolarity', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='sentiWordNetCountpol',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='stanfordNLPCountpol',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='textblobCountpol',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='vaderCountpol',
        ),
        migrations.AddField(
            model_name='requestresult',
            name='hashtagFrequent',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='negativeTopFrequentHashtag',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='negativeTopFrequentWords',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='negativeWordCloudFilename',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='negativeWordcounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='positiveTopFrequentHashtag',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='positiveTopFrequentWords',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='positiveWordCloudFilename',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='positiveWordcounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='sentiWordNetCountpol',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='sentiWordnetCountpol_sentence',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='sortedF1ScoreList',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='stanfordNLPCountpol',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='stanfordNLPCountpol_sentence',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='textblobCountpol',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='textblobCountpol_sentence',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='topFrequentWords',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='vaderCountpol',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='vaderCountpol_sentence',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='wordCloudFileName',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='wordCounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='kappa',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='sentenceKappa',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='sentiWordnetAverage',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='sentiWordnetMajority',
            field=models.TextField(default='something'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='stanfordNLPMajority',
            field=models.TextField(default='something'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='textblobAverage',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='textblobMajority',
            field=models.TextField(default='something'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='vaderAverage',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='vaderMajority',
            field=models.TextField(default='something'),
        ),
    ]
