# Generated by Django 2.2.5 on 2019-09-27 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0002_auto_20190717_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestlist',
            fields=[
                ('user_number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('project_number', models.IntegerField(default=0)),
                ('request_status', models.TextField(default='fail')),
            ],
        ),
        migrations.CreateModel(
            name='SAResult',
            fields=[
                ('ids', models.CharField(default='SOME STRING', max_length=200, primary_key=True, serialize=False)),
                ('tweetContent', models.CharField(default='SOME STRING', max_length=200)),
                ('vaderTweetScore', models.FloatField(default=150.0)),
                ('vaderTweetPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('textblobTweetScore', models.FloatField(default=150.0)),
                ('textblobTweetPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('stanfordNLPTweetPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('sentiWordNetTweetScore', models.FloatField(default=150.0)),
                ('sentiWordNetTweetPolarity', models.CharField(default='SOME STRING', max_length=200)),
                ('tweetKappa', models.FloatField(default=150.0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
