# Generated by Django 2.2.5 on 2019-09-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0003_auto_20190926_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SAResult',
        ),
        migrations.RenameField(
            model_name='requestlist',
            old_name='user_number',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='project_number',
            field=models.TextField(default='something'),
        ),
    ]
