# Generated by Django 2.2.4 on 2019-12-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0003_tasklist_ismailsended'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresult',
            name='tweetIDs',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
    ]
