# Generated by Django 2.2.5 on 2019-09-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0004_auto_20190930_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlist',
            name='project_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='user_id',
            field=models.TextField(default='something', primary_key=True, serialize=False),
        ),
    ]
