# Generated by Django 2.2.4 on 2019-12-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0004_requestresult_tweetids'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresult',
            name='wordGraphFilename',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
