# Generated by Django 2.2.5 on 2019-10-01 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0005_auto_20190930_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlist',
            old_name='request_status',
            new_name='project_status',
        ),
    ]
