# Generated by Django 2.2.4 on 2019-12-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0005_requestresult_wordgraphfilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenceresult',
            name='sentence_content',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
