# Generated by Django 2.2.4 on 2019-10-04 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0006_auto_20190930_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlist',
            name='request_completed_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='request_content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='request_issued_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
