# Generated by Django 2.2.4 on 2019-12-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0007_auto_20191217_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresult',
            name='annotations',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='f1score_max',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='neg_f1score_max',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='neu_f1score_max',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='pos_f1score_max',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='sentiPolarities',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='sentiWord_neg_f1score',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='sentiWord_neu_f1score',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='sentiWord_pos_f1score',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='stanPolarities',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='stanfordNLP_neg_f1score',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='stanfordNLP_neu_f1score',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='stanfordNLP_pos_f1score',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='textblobPolarities',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='textblob_neg_f1score',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='textblob_neu_f1score',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='textblob_pos_f1score',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='vaderPolarities',
            field=models.CharField(default='SOME STRING', max_length=10000000),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='vader_neg_f1score',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='vader_neu_f1score',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='requestresult',
            name='vader_pos_f1score',
            field=models.FloatField(default=150.0),
        ),
    ]
