# Generated by Django 2.2.4 on 2019-10-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0007_auto_20191004_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlist',
            old_name='user_id',
            new_name='request_id',
        ),
        migrations.RenameField(
            model_name='requestlist',
            old_name='project_status',
            new_name='request_status',
        ),
        migrations.RemoveField(
            model_name='requestlist',
            name='project_number',
        ),
        migrations.AddField(
            model_name='requestlist',
            name='request_owner',
            field=models.TextField(default='something'),
        ),
    ]
